---
#
# Ansible managed
#
repository:
  description: Install and configure auditd on your system.
  homepage: https://robertdebock.nl/
  topics: auditd, system, monitoring, security, ansible, molecule, tox, playbook
